import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.FBH_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())

// FoxyBear rebrand (OQ6=remove): strip opencode SaaS providers from the snapshot.
// The build regenerates this file from models.dev on every run; without this filter,
// the opencode provider (phones home to api.opencode.ai) would be re-added.
const snapshot = JSON.parse(modelsData)
for (const key of Object.keys(snapshot)) {
  if (key.toLowerCase().includes("opencode")) {
    delete snapshot[key]
  }
}
const filteredData = JSON.stringify(snapshot)

await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${filteredData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log(`Generated models-snapshot.js (${Object.keys(snapshot).length} providers, opencode stripped)`)
